apiVersion: apps/v1
kind: Deployment
metadata:
  metadata:
  labels:
    app.kubernetes.io/name: netflix
    app.kubernetes.io/instance: netflix
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: netflix-rolling-update
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
        role: rolling-update
    spec:
      containers:
      - image: 145282914747.dkr.ecr.us-east-2.amazonaws.com/sample-app:4
        imagePullPolicy: Always
        name: netflix
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
